name: "Build Raven Backend and push to container registry"

on:
  push:
    branches:
      - "dev"
      - "main"
  pull_request:
    branches:
      - "dev"
      - "main"
permissions:
  contents: read

jobs:
  run-tests:
    name: Run tests with gradle
    runs-on: ubuntu-latest

    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup JDK v17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3

      - name: Run all tests
        run: |
          chmod +x ./gradlew
          ./gradlew test          

  build-docker-image:
    name: Build Docker Image
    runs-on: ubuntu-latest
    steps:
      - name: Get current Branch
        run: echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV

      - name: Get code
        uses: actions/checkout@v4

      - name: Setup QEMU for Multi-Architecture Builds
        uses: docker/setup-qemu-action@v2

      - name: Setup Docker BuildX
        uses: docker/setup-buildx-action@v2

      - name: Log into Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Application and push image
        uses: docker/build-push-action@master
        with:
          context: .
          platforms: linux/amd64,linux/arm64/v8
          push: true
          tags: ghcr.io/nihaiden/linkkistl-server:${{ env.BRANCH }}

